### PR TITLE
allow to config other download server for maven-wrapper.jar

### PR DESCRIPTION
**Pull request by reinsch82**
this was suggested [here](https://github.com/takari/maven-wrapper/issues/95)

as my other [PR](https://github.com/takari/maven-wrapper/pull/96) on maven-wrappper this allows for better usage in restricted environments

### CODE REVIEW

**Comment by adrianshum** [comment]
I am thinking of implementing https://github.com/takari/maven-wrapper/issues/95 , it will be great if you can save the {{downloadBaseUrl}} into wrapper.properties if it is provided

**Comment by reinsch82** [comment]
the url is in there as part of the distribution url, isn't that enough?

**Comment by mosabua** [comment]
Please do not pull a massive library like guava into the wrapper for a string manipulation method. Remove that dependency and I will have another look soon.

**Comment by reinsch82** [comment]
This was a dependency already and it is just for the plugin, not for the actual wrapper.
I understand the need to keep the wrapper small. @mosabua

**Comment by adrianshum** [comment]
> the url is in there as part of the distribution url, isn't that enough?

`distributionUrl` is for downloading the Maven distribution.  However, we also need to override the URL for downloading the Wrapper JAR, for which is currently hardcoded as `https://repo1.maven.org/...`.

**Comment by reinsch82** [comment]
@adrianshum in this PR there is a `downloadBaseUrl` you can provide via command line. This is used to get the wrapper AND the distribution. the fact that there where 2 different URLs for wrapper and distribution doesn't seem to be necessary and maybe even was in there by accident.

**Comment by adrianshum** [comment]
@reinsch82 from my understanding it is not the case:  There is a feature in the wrapper script itself, when wrapper JAR is not available, it will try to download the wrapper JARs.  Currently it is hardcoded to download from repo1.maven.org. 

In this PR, it is just instructing the *plugin* to download the wrapper.  However we want similar feature to be available in the *wrapper* itself.  

Given the wrapper properties could be set up by the *plugin*, and *plugin* is having downloadBaseUrl as input param for its wrapper download, I believe it is reasonable to save this as part of the properties so that the *wrapper* can make use of it.

I think it is debatable whether we really need 2 separate URL for wrapper AND distribution, and that's the reason in my original suggestion (https://github.com/takari/maven-wrapper/issues/95) that user could simply provide downloadBaseUrl and it will be used for all kind of downloads.  However, for the sake of backward compatibility, I think we should keep the distributionUrl so new wrapper and plugin will still work as is

**Comment by reinsch82** [comment]
@adrianshum I get your point.
Maybe @mosabua can help? Why are there 2 separate URLs? Both provide maven-wrapper versions starting with 0.1.
Also I couldn't find any reference in the MVNW shell and batch files to repo1. It got replaced [here](https://github.com/takari/maven-wrapper/commit/db3d4e69020d53defcce9b33f532ae0c802af1ad#diff-7f6d424362f5b03d9b91a80a1e43eefe)

It looks intentional to get rid of repo1.

**Comment by adrianshum** [comment]
Have just had time to take a look into the wrapper code.  Turned out there is already feature I was suggesting (kind of).

The URL for the wrapper script to download wrapper-JAR can already be defined in the `maven-wrapper.properties` with the key `wrapperUrl` (which is the `wrapperJarDownloadUrl` I was suggesting in my issue).  However currently there is no logic in the plugin to populate such entry.

Therefore, if you can populate such property based on downloadBaseUrl, it should already complete the feature I was originally thinking of

**Comment by adrianshum** [comment]
I dunno how I should contribute to your pull request... Basically it is by changing the following lines:

```
     String wrapperUrl = String.format("%s/%s", getDownloadBaseUrl(), artifactPath);
+    String wrapperJarUrl = String.format("%s/io/takari/maven-wrapper/%s/maven-wrapper-%s.jar", getDownloadBaseUrl(), version, version);

```
...
```
-    overwriteDistributionUrl(rootDirectory, getDistributionUrl());
+    overwriteDistributionUrl(rootDirectory, getDistributionUrl(), wrapperJarUrl);
```
and change overwriteDistributionUrl() to
```
    // better name it to something like overwriteMavenWrapperProperties() ?
  private void overwriteDistributionUrl(Path rootDirectory, String distributionUrl, String wrapperJarUrl) throws IOException {
    List<String> properties = new ArrayList<>();
    if (!isNullOrEmpty(distributionUrl)) {
        properties.add("distributionUrl=" + distributionUrl);
    }
    if (!isNullOrEmpty(wrapperJarUrl)) {
        properties.add("wrapperUrl=" + wrapperJarUrl);
    } 
    if (!properties.empty()) {
      Path wrapperProperties = rootDirectory.resolve(Paths.get(".mvn", "wrapper", "maven-wrapper.properties"));
      if (Files.isWritable(wrapperProperties)) {
        Files.write(wrapperProperties, properties, Charset.forName("UTF-8"));
      }
    }
  }
```

That should do the work of populating `wrapperUrl` in `maven-wrapper.properties`

(Though I prefer it only populating the entry if user have overriden `downloadBaseUrl` and `distributionUrl` , I dare not to touch your change too much)

**Comment by mosabua** [comment]
Merged alternate PR

**Pull request closed without merging**
