### PR TITLE
Added support for settings.xml location properties

### PR DESCRIPTION
**Pull request by garethahealy**
https://github.com/takari/takari-maven-plugin/issues/11

### CODE REVIEW

**Comment by mosabua** [comment]
What kind of testing did you do with this?

**Comment by garethahealy** [comment]
Tested the following:

1. Standard setup, i.e.: /home/user/.m2
2. With settings.xml using different local repo, i.e.: /tmp/.m2
3. With settings.xml without local repo specified - defaults to /home/user/.m2
4. With a mirror set for all, i.e.: via nexus
5. Without a mirror set, i.e.: via maven central

**Comment by mosabua** [comment]
Great. Could you please sign the Takari CLA .. then I can proceed with testing and merge and release.

**Comment by mosabua** [comment]
http://takari.io/support/TakariCLA.pdf

**Comment by garethahealy** [comment]
Signed

**Comment by garethahealy** [comment]
@mosabua ; is this OK to be merged?

**Comment by mosabua** [comment]
Will clean up after merge and test it all in detail

**Pull request merged**
